apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: k2lv8vm70-go 
  janus-idp.io/tekton: k2lv8vm70-go
  backstage.io/kubernetes-id: k2lv8vm70-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: k2lv8vm70-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml